/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //getStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  //devsSidebar: [{type: 'autogenerated', dirName: 'devs'}],
  //pmsSidebar: [{type: 'autogenerated', dirName: 'pms'}],
  //gtmLeadersSidebar: [{type: 'autogenerated', dirName: 'gtm-leaders'}],
  //openApiSidebar: [{ type: "autogenerated", dirName: "public_apis" }],
  getStartedSidebar: [
    {
      type: 'category', 
      label: 'Getting Started',
      items: [
        'getting-started/intro',
        {
          type: 'category', 
          label: 'Build',
          items: [
            'getting-started/build/self-serve',
            'getting-started/build/workflow-canvas',
          ]
        }
      ]
    }
  ],
  devsSidebar: [
    {
      type: 'category', 
      label: 'For Developers',
      link: {
        type: 'generated-index',
        title: "Documentation for Developers",
        description: "Documentation for Developers",
        keywords: ["devs"],
      },
      items: [
        {
          type: 'category', 
          label: 'Configure',
          items: [
            'devs/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'devs/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'devs/go-live/intro',
          ]
        },
      ]
    }
  ],
  pmsSidebar: [
    {
      type: 'category', 
      label: 'For Product Managers',
      link: {
        type: 'generated-index',
        title: "Documentation for Product Managers",
        description: "Documentation for Product Managers",
        keywords: ["pms"],
      },
      items: [
        {
          type: 'category', 
          label: 'Configure',
          items: [
            'pms/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'pms/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'pms/go-live/intro',
          ]
        },
      ]
    }
  ],
  gtmLeadersSidebar: [
    {
      type: 'category', 
      label: 'For GTM Leaders',
      link: {
        type: 'generated-index',
        title: "Documentation for GTM Leaders",
        description: "Documentation for GTM Leaders",
        keywords: ["gtm"],
      },
      items: [
        {
          type: 'category', 
          label: 'Configure',
          items: [
            'gtm-leaders/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'gtm-leaders/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'gtm-leaders/go-live/intro',
          ]
        },
      ]
    }
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Thrive APIs",
      link: {
        type: "generated-index",
        title: "Instrumentation API",
        description:
          "Documentation for Instrumentation API",
      },
      // @ts-ignore
      items: require("./docs/public_apis/sidebar.js")
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
