/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //getStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  //devsSidebar: [{type: 'autogenerated', dirName: 'devs'}],
  //pmsSidebar: [{type: 'autogenerated', dirName: 'pms'}],
  //gtmLeadersSidebar: [{type: 'autogenerated', dirName: 'gtm-leaders'}],
  //openApiSidebar: [{ type: "autogenerated", dirName: "public_apis" }],
  getStartedSidebar: [
    {
      type: 'category', 
      label: 'Getting Started',
      items: [
        'getting-started/intro',
        {
          type: 'category', 
          label: 'Build',
          link: {
            type: 'generated-index',
            title: "Build",
            description: "Get started with ThriveStack's Build Module",
            keywords: ["build"],
          },
          items: [
            {
              type: 'category', 
              label: 'Self Serve',
              link: {
                type: 'generated-index',
                title: 'Self Serve',
                description: "Self Serve Documentation",
                keywords: ["self-serve"],
              },
              items: [
                'getting-started/build/self-serve/self-serve',
                'getting-started/build/self-serve/workflow-canvas',
                'getting-started/build/self-serve/invitation',
                'getting-started/build/self-serve/triggers',
                'getting-started/build/self-serve/publish',
                'getting-started/build/self-serve/promote',
              ]
            },
            {
              type: 'category', 
              label: 'Instrumentation',
              link: {
                type: 'generated-index',
                title: "Instrumentation",
                description: "Get started with ThriveStack's Instrumentation Module",
                keywords: ["instrumentation"],
              },
              items: [
                {
                  type: 'category', 
                  label: 'Identification',
                  link: {
                    type: 'generated-index',
                    title: 'Identification',
                    description: 'Identification Docs',
                    keywords: ['identification'],
                  },
                  items: [
                    'getting-started/build/instrumentation/identification/overview',
                    'getting-started/build/instrumentation/identification/user',
                    'getting-started/build/instrumentation/identification/group',
                  ]
                },
                {
                  type: 'category', 
                  label: 'Events',
                  items: [
                  'getting-started/build/instrumentation/events/standard/overview',
                  {
                    type: 'category', 
                    label: 'Standard',
                    link: {
                      type: 'generated-index',
                      title: 'Standard',
                      description: 'Standard Docs',
                      keywords: ['standard-events'],
                    },
                    items: [
                      'getting-started/build/instrumentation/events/standard/signed_up',
                      'getting-started/build/instrumentation/events/standard/account_created',
                      'getting-started/build/instrumentation/events/standard/account_added_user',
                      'getting-started/build/instrumentation/events/standard/signed_in',
                      'getting-started/build/instrumentation/events/standard/signed_out',
                      'getting-started/build/instrumentation/events/standard/invite_sent',
                      'getting-started/build/instrumentation/events/standard/trial_started',
                      'getting-started/build/instrumentation/events/standard/trial_ended',
                      'getting-started/build/instrumentation/events/standard/account_removed_user',
                      'getting-started/build/instrumentation/events/standard/account_deleted',
                    ]
                  },
                  ]
                },
              ]
            },
          ]
        },
        {
          type: 'category', 
          label: 'Analyze',
          link: {
            type: 'generated-index',
            title: 'Analyze',
            description: "Get started with ThriveStack's Analyze Module",
            keywords: ['analyze'],
          },
          items: [
            {
              type: 'category', 
              label: 'Reports',
              items: [
                'getting-started/analyze/reports/overview'
              ]
            },
          ]
        },
      ]
    }
  ],
  devsSidebar: [
    {
      type: 'category', 
      label: 'For Developers',
      link: {
        type: 'generated-index',
        title: "Documentation for Developers",
        description: "Documentation for Developers",
        keywords: ["devs"],
      },
      items: [
        {
          type: 'category', 
          label: 'Customize',
          items: [
            'devs/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'devs/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'devs/go-live/intro',
          ]
        },
      ]
    }
  ],
  pmsSidebar: [
    {
      type: 'category', 
      label: 'For Product Managers',
      link: {
        type: 'generated-index',
        title: "Documentation for Product Managers",
        description: "Documentation for Product Managers",
        keywords: ["pms"],
      },
      items: [
        {
          type: 'category', 
          label: 'Customize',
          items: [
            'pms/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'pms/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'pms/go-live/intro',
          ]
        },
      ]
    }
  ],
  gtmLeadersSidebar: [
    {
      type: 'category', 
      label: 'For GTM Leaders',
      link: {
        type: 'generated-index',
        title: "Documentation for GTM Leaders",
        description: "Documentation for GTM Leaders",
        keywords: ["gtm"],
      },
      items: [
        {
          type: 'category', 
          label: 'Customize',
          items: [
            'gtm-leaders/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'gtm-leaders/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'gtm-leaders/go-live/intro',
          ]
        },
      ]
    }
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Thrive APIs",
      link: {
        type: "generated-index",
        title: "Instrumentation API",
        description:
          "Documentation for Instrumentation API",
      },
      // @ts-ignore
      items: require("./docs/public_apis/sidebar.js")
    }
  ],
  graphQLApiSidebar: [{type: 'autogenerated', dirName: 'schema'}]
};

module.exports = sidebars;
