/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */


const dev = [
    {
      type: 'category', 
      label: 'Developers 👩‍💻',
      link: {
        type: 'generated-index',
        title: "Documentation for Developers",
        description: "Documentation for Developers",
        keywords: ["devs"],
      },
      items: [
        {
          type: 'category', 
          label: 'Customize',
          items: [
            'devs/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'devs/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'devs/go-live/intro',
          ]
        },
      ]
    }
  ]

const pms = [
    {
      type: 'category', 
      label: 'Growth 🌱',
      link: {
        type: 'generated-index',
        title: "Documentation for Growth Leaders",
        description: "Documentation for Growth Leaders",
        keywords: ["pms"],
      },
      items: [
        {
          type: 'category', 
          label: 'Customize',
          items: [
            'pms/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'pms/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'pms/go-live/intro',
          ]
        },
      ]
    }
  ]

const gtm = [
    {
      type: 'category', 
      label: 'GTM Leaders 🚀',
      link: {
        type: 'generated-index',
        title: "Documentation for GTM Leaders",
        description: "Documentation for GTM Leaders",
        keywords: ["gtm"],
      },
      items: [
        {
          type: 'category', 
          label: 'Customize',
          items: [
            'gtm-leaders/configure/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Integrate',
          items: [
            'gtm-leaders/integrate/intro',
          ]
        },
        {
          type: 'category', 
          label: 'Go Live',
          items: [
            'gtm-leaders/go-live/intro',
          ]
        },
      ]
    }
  ]

const graphql = [
  {
    type: 'autogenerated',
    dirName: 'public_apis/schema'
  }
]

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  getStartedSidebar: [
    {
      type: 'category', 
      label: 'Getting Started 🌟',
      items: [
        'getting-started/intro',
        {
          type: 'category', 
          label: 'Personas 👥',
          link: {
            type: 'generated-index',
            title: 'Personas',
            description: "Persona Level Documentation",
            keywords: ["personas"],
          },
          items: [...dev, ...pms, ...gtm],
        },
        {
          type: 'category', 
          label: 'SELF SERVE 🛎️',
          link: {
            type: 'generated-index',
            title: 'Self Serve',
            description: "Self Serve Documentation",
            keywords: ["self-serve"],
          },
          items: [
            {
              type: 'category',
              label: 'APIs',
              items: [
                'getting-started/self-serve/apis/intro',
                'getting-started/self-serve/apis/triggers',
                'getting-started/self-serve/apis/invitation',
                'getting-started/self-serve/apis/onboarding',
                'getting-started/self-serve/apis/publish',
                'getting-started/self-serve/apis/promote',
              ]
            },
            'getting-started/self-serve/self-serve',
            'getting-started/self-serve/workflow-canvas',
          ]
        },
        {
          type: 'category', 
          label: 'ANALYZE 📈',
          link: {
            type: 'generated-index',
            title: 'Analyze',
            description: "Get started with ThriveStack's Analyze Module",
            keywords: ['analyze'],
          },
          items: [
          "getting-started/analyze/intro",
          "getting-started/analyze/authentication",
          {
            type: 'category', 
            label: 'Instrumentation',
            link: {
              type: 'generated-index',
              title: "Instrumentation",
              description: "Get started with ThriveStack's Instrumentation Module",
              keywords: ["instrumentation"],
            },
            items: [
              'getting-started/analyze/instrumentation/overview',
              {
                type: 'category', 
                label: 'Identification',
                link: {
                  type: 'generated-index',
                  title: 'Identification',
                  description: 'Identification Docs',
                  keywords: ['identification'],
                },
                items: [
                  //'getting-started/analyze/instrumentation/identification/overview',
                  'getting-started/analyze/instrumentation/identification/user',
                  'getting-started/analyze/instrumentation/identification/group',
                ]
              },
              {
                type: 'category', 
                label: 'Events',
                items: [
                'getting-started/analyze/instrumentation/events/event-tracking',
                {
                  type: 'category', 
                  label: 'Standard',
                  link: {
                    type: 'generated-index',
                    title: 'Standard',
                    description: 'Standard Docs',
                    keywords: ['standard-events'],
                  },
                  items: [
                    'getting-started/analyze/instrumentation/events/standard/signed_up',
                    'getting-started/analyze/instrumentation/events/standard/account_created',
                    'getting-started/analyze/instrumentation/events/standard/account_added_user',
                    'getting-started/analyze/instrumentation/events/standard/signed_in',
                    'getting-started/analyze/instrumentation/events/standard/signed_out',
                    'getting-started/analyze/instrumentation/events/standard/invite_sent',
                    'getting-started/analyze/instrumentation/events/standard/trial_started',
                    'getting-started/analyze/instrumentation/events/standard/trial_ended',
                    'getting-started/analyze/instrumentation/events/standard/account_removed_user',
                    'getting-started/analyze/instrumentation/events/standard/account_deleted',
                  ]
                },
                ]
              },
              "getting-started/analyze/instrumentation/page",
            ]
          },
            {
              type: 'category', 
              label: 'Reports',
              items: [
                'getting-started/analyze/reports/overview',
                {
                  type: 'category', 
                  label: 'Standard',
                  link: {
                    type: 'generated-index',
                    title: 'Standard',
                    description: 'Standard Reports Docs',
                    keywords: ['standard-reports'],
                  },
                  items: [
                    'getting-started/analyze/reports/standard/acquisition',
                    'getting-started/analyze/reports/standard/activation',
                    'getting-started/analyze/reports/standard/retention',
                    'getting-started/analyze/reports/standard/engagement',
                    'getting-started/analyze/reports/standard/expansion',
                  ]
                },
              ]
            },
          ]
        },
      ]
    }
  ],
  devsSidebar: dev,
  pmsSidebar: pms,
  gtmLeadersSidebar: gtm,
  apiSidebar: [
    {
      type: "category",
      label: "Analyze APIs",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "Documentation for APIs",
      },
      // @ts-ignore
      items: [
        require("./docs/public_apis/sidebar.js"),
      ]
    },
    {
      type: "category",
      label: "Self Serve APIs",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "Documentation for APIs",
      },
      // @ts-ignore
      items: [
        graphql,
      ]
    }
  ],
};

module.exports = sidebars;
